alter session set container = dbsys;
CONNECT g2404/pass@localhost/dbsys

-- バージョン管理用テーブルの作成
create table table_versions (
   table_name     varchar2(255) primary key,
   version_number number not null,
   modified_at    timestamp with local time zone not null
);

create table categories (
   category_id        number generated by default as identity primary key,
   parent_category_id number
      references categories ( category_id ),
   category_name      varchar2(100) not null,
   sort_order         number default 0 not null,
   created_at         timestamp with local time zone default sysdate not null,
   updated_at         timestamp with local time zone default sysdate not null
);
create index idx_categories_parent_category_id on
   categories (
      parent_category_id
   );
create trigger trg_categories_change after
   insert or update or delete on categories
begin
   update table_versions
      set version_number = version_number + 1,
          modified_at = systimestamp
    where table_name = 'categories';
end;
/

create table menus (
   menu_id     number generated by default as identity primary key,
   menu_name   varchar2(254) not null,
   category_id number not null
      references categories ( category_id ),
   menu_price  number(16) not null,
   menu_image  varchar2(511) not null,
   sort_order  number default 0 not null,
   created_at  timestamp with local time zone default sysdate not null,
   deleted_at  timestamp with local time zone default null
);
create trigger trg_menus_change after
   insert or update or delete on menus
begin
   update table_versions
      set version_number = version_number + 1,
          modified_at = systimestamp
    where table_name = 'menus';
end;
/

create table options (
   option_id         number generated by default as identity,
   menu_id           number
      references menus ( menu_id ),
      -- references options ( option_id ),
   option_price      number(16) not null,
   option_name       varchar2(254) not null,
   option_deleted_at timestamp with local time zone default null,
   constraint pk_options primary key ( menu_id,
                                       option_id )
);
create trigger trg_options_change after
   insert or update or delete on options
begin
   update table_versions
      set version_number = version_number + 1,
          modified_at = systimestamp
    where table_name = 'options';
end;
/

create table device_types (
   device_type_id   number primary key,
   device_type_name varchar2(254) not null
);

create table tables (
   table_id       number primary key,
   table_name     varchar2(254) not null,
   table_capacity number not null
);

create table devices (
   device_id      raw(16) primary key,
   device_name    varchar2(254) not null,
   device_type_id number not null
      references device_types ( device_type_id ),
   table_id       number
      references tables ( table_id )
);

create table customer_statuses (
   customer_status_id           number primary key,
   customer_status_display_name varchar2(254) not null
);

create table customers (
   customer_id        raw(16) primary key,
   table_id           number
      references tables ( table_id ),
   visited_at         timestamp with local time zone default sysdate not null,
   paid_at            timestamp with local time zone default null,
   customer_status_id number default 1 not null
      references customer_statuses ( customer_status_id ),
   customer_count     number not null
);

--orders 
create table order_statuses (
   order_status_id                    number primary key,
   order_status_display_name_staff    varchar2(254) not null,
   order_status_display_name_customer varchar2(254) not null
);

create table orders (
   order_id        raw(16),
   menu_id         number
      references menus ( menu_id ),
   order_status_id number default 1 not null
      references order_statuses ( order_status_id ),
   ordered_at      timestamp with local time zone default sysdate not null,
   cooked_at       timestamp with local time zone default null,
   customer_id     raw(16) not null
      references customers ( customer_id ),
   constraint pk_orders primary key ( order_id,
                                      menu_id )
);

create table order_options (
   order_id  raw(16),
   menu_id   number,
   option_id number,
   constraint fk_order_options_orders
      foreign key ( order_id,
                    menu_id )
         references orders ( order_id,
                             menu_id ),
   constraint fk_order_options_menu_options
      foreign key ( menu_id,
                    option_id )
         references options ( menu_id,
                              option_id ),
   constraint pk_order_options primary key ( order_id,
                                             menu_id,
                                             option_id )
);

create view v_active_menus as
   select *
     from menus
    where deleted_at is null
    order by sort_order asc;

create view v_options_linked_active_menus as
   select menu_id,
          option_id,
          option_name,
          option_price,
          option_deleted_at
     from options
     join v_active_menus
   using ( menu_id );

create view v_active_customers as
   select *
     from customers
    where paid_at is null;

-- Users
create table users (
   user_id       number generated by default as identity primary key,
   username      varchar2(254) not null,
   password_hash raw(32) not null,
   salt          raw(16) not null,
   constraint uq_users_username unique ( username )
);

-- カテゴリの階層制限トリガーの作成
create trigger trg_categories_depth before
   insert or update on categories
   for each row
   when ( new.parent_category_id is not null )
declare
   v_parent_parent_id categories.parent_category_id%type;
begin
   select parent_category_id
     into v_parent_parent_id
     from categories
    where category_id = :new.parent_category_id;

   if v_parent_parent_id is not null then
      raise_application_error(
         -20001,
         'カテゴリは2階層までしか許可されていません'
      );
   end if;
end;
/

